version: "2"

run:
  timeout: 5m
  go: "1.24"

linters:
  # Use fast linters for better performance
  default: fast
  enable:
    - govet
    - errcheck
    - gosec
    - ineffassign
    - unused
    - wsl_v5
    - contextcheck
    - staticcheck
    
  disable:
    - cyclop  # Too strict
    - depguard  # Allow internal imports
    - err113  # Allow dynamic errors
    - exhaustruct  # Too strict for tests
    - forcetypeassert  # Allow in tests
    - funlen  # Allow longer functions
    - gocognit  # Too strict
    - goconst  # Not critical
    - godot  # Not critical
    - intrange  # Go 1.22+ feature
    - lll  # Line length not critical
    - mnd  # Magic numbers acceptable
    - nestif  # Allow nested if
    - nlreturn  # Not critical
    - paralleltest  # Not critical
    - perfsprint  # Not critical
    - revive  # Too many false positives
    - tagliatelle  # YAML tags fine
    - testpackage  # Allow test packages
    - varnamelen  # Variable names fine
    - wsl  # Deprecated, using wsl_v5 instead

  settings:
    gosec:
      # Allow some security warnings
      excludes:
        - G204  # Subprocess launched with variable - inputs are validated and sanitized
        - G304  # Potential file inclusion via variable - path is validated and comes from trusted config

formatters:
  enable:
    - gci
    - gofmt