run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused

issues:
  exclude-rules:
    # Exclude typecheck errors for yaml imports
    - linters:
        - typecheck
      text: "undefined: yaml"

