server:
  host: "0.0.0.0"
  port: 8080
  # enable_web_ui and enable_health not specified - should default to true

logging:
  level: "debug"
  format: "json"

metrics:
  collection:
    default_interval: "30s"
