server:
  host: "0.0.0.0"
  port: 8080
  enable_web_ui: false    # Disable web UI
  enable_health: true    # Keep health endpoint enabled

logging:
  level: "debug"
  format: "json"

metrics:
  collection:
    default_interval: "30s"
