name: Release Please

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: googleapis/release-please-action@v4
      id: release_please
      with:
        release-type: go
        path: .
        token: ${{ secrets.GITHUB_TOKEN }}

    # Debug info
    - name: Debug Release Info
      if: steps.release_please.outputs.release_created == 'true'
      run: |
        echo "Release created!"
        echo "Tag: ${{ steps.release_please.outputs.tag_name }}"
        echo "Name: ${{ steps.release_please.outputs.name }}"
        echo "Draft: ${{ steps.release_please.outputs.draft }}"
        echo "Prerelease: ${{ steps.release_please.outputs.prerelease }}"

